# VeriRAG Tools
#
# This module contains external tools used by the agent.
#
# Currently:
# - Tavily web search
#
# The agent uses web search only when the uploaded/permanent
# document retrieval is not sufficient to answer the question.


from langchain_tavily import TavilySearch

from app.config import TAVILY_MAX_RESULTS


# Create Tavily search tool

tavily_search = TavilySearch(
    max_results=TAVILY_MAX_RESULTS,
)


def web_search(
    query: str,
) -> list[dict]:
    """
    Search the web using Tavily.

    Parameters
    ----------
    query : str
        Search query generated by the query-rewriting step.

    Returns
    -------
    list[dict]
        Individual Tavily search results.

    Returns an empty list if the query is empty or
    the search response does not contain results.
    """

    # Avoid making an unnecessary web request.

    if not query or not query.strip():
        return []

    response = tavily_search.invoke(
        query.strip()
    )

    # Tavily normally returns a dictionary containing
    # a "results" list.

    if not isinstance(response, dict):
        return []

    results = response.get(
        "results",
        [],
    )

    if not isinstance(results, list):
        return []

    return results